# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GraphTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GraphTutorial
  pod 'MSAL', '~> 0.3.0'
  pod 'MSGraphMSALAuthProvider', '~> 0.1.1'
  pod 'MSGraphClientSDK', ' ~> 0.1.3'
  pod 'MSGraphClientModels', '~> 0.1.1'

  target 'GraphTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GraphTutorialUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
